name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci && npm run build

      - run: cp -r ./dist/smart-documentation-app ~

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - run: rm -rf *

      - run: cp -r ~/smart-documentation-app .

      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "[automated] Deplyed against ${{github.sha}}"
